<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fbdf07ec-eded-4d35-acf9-ded22c800a4b</testSuiteGuid>
   <testCaseLink>
      <guid>5479289d-071d-45c5-a89b-2a5255ff938d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenLoginTest</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a31c0bf9-9f8b-4714-b744-8ad79ce11f61</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a31c0bf9-9f8b-4714-b744-8ad79ce11f61</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>deniz</value>
         <variableId>2f6c6e31-ee80-4ade-8cef-89c2ac05ec7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a31c0bf9-9f8b-4714-b744-8ad79ce11f61</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>deniz123</value>
         <variableId>de1fa766-a3d7-4d6e-b909-3be68100a83d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
