<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IndiaUnited StatesCanadaAustraliaIsr_09757b</name>
   <tag></tag>
   <elementGuidId>9ea28f7a-2b5a-4780-b6d8-bf8f608f4240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#country</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Country *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1e2a79fb-4c3f-484c-a644-9ced01080245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>8edbc65b-4e14-4558-a97a-d3e52abda795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>1b046500-8e25-4f84-9633-5d25ae31ea24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>f7cf4867-9462-41a6-9d45-3a04b362ea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e6e9036a-cb2d-4abb-ad62-b283bf6a0960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								India
								United States
								Canada
								Australia
								Israel
								New Zealand
								Singapore
							</value>
      <webElementGuid>0562eafb-f870-438e-b9fb-5c1c4dea54b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country&quot;)</value>
      <webElementGuid>cd6aa2ac-dcc3-47a9-a632-76c84940ae09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='country']</value>
      <webElementGuid>03408d8b-9476-4eeb-8e3d-3a9f2778566a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[6]/select</value>
      <webElementGuid>5dffac92-ceb2-4f72-bfd7-38bd1832cc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>57c2f65f-60b0-4e6e-aeb2-c816ee892dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>551dcbde-c4cb-4084-8b02-a767d5525a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/select</value>
      <webElementGuid>995e26a0-5228-46d0-baae-4f7680069fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'country' and @name = 'country' and (text() = '
								India
								United States
								Canada
								Australia
								Israel
								New Zealand
								Singapore
							' or . = '
								India
								United States
								Canada
								Australia
								Israel
								New Zealand
								Singapore
							')]</value>
      <webElementGuid>823d0dc3-4a2b-4389-b050-2a51778f488d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
