<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MonthJanuaryFebruaryMarchAprilMayJun_aa9ebb</name>
   <tag></tag>
   <elementGuidId>d50a1721-7c0b-4582-a632-ddf628668e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='months']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#months</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#months</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>49a0d198-9dc6-4528-9776-19533e915fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>22c6bb45-226f-4f34-9e9d-e0f60e51d316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>d6afc7df-b5cb-4ba6-86da-30487d445481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>1515d311-e75a-472b-b2c3-1acad03484c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>308589f6-0623-43dc-963d-cf0c33b94cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										</value>
      <webElementGuid>46ddc8af-1a36-4bfc-acb1-300d3420ccbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;months&quot;)</value>
      <webElementGuid>b98136ed-c278-48ae-af25-e1c8c4aa1920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='months']</value>
      <webElementGuid>1f43e60c-6671-468e-b610-21d62bd0de23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-months']/select</value>
      <webElementGuid>e874192a-17aa-4561-bc4c-e8b66c3de90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::select[2]</value>
      <webElementGuid>05a435d3-2d08-48c2-84d0-6bae713f90d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[2]</value>
      <webElementGuid>0fea4e04-c349-4a81-9d73-88dab2f05216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for our newsletter!'])[1]/preceding::select[2]</value>
      <webElementGuid>fb61f0dc-e560-476c-9c61-7a4d426b0ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive special offers from our partners!'])[1]/preceding::select[2]</value>
      <webElementGuid>747ef170-1719-488e-8726-304c3fd964c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>19cfd299-efd0-4da1-b1ea-e93659d2f11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'months' and @name = 'months' and (text() = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										' or . = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										')]</value>
      <webElementGuid>0519c697-1224-4bd0-af37-f6e57ea970f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
